<?php /* Smarty version 2.6.18, created on 2008-01-24 23:53:03
         compiled from d:%5Cmy+webs+1%5Ctnt-synergy-3.0%5Cdev%5Cwww%5Cincludes%5Clibs%5Ctnt%5Cwui%5Ctests/simple.html */

$this->_cache_serials['d:/my webs 1/tnt-synergy-3.0/dev/www/temp/templates\%%09^09F^09FCF8A5%%simple.html.inc'] = '49db963e012013586829e4992ad2a59f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
_smarty_load_directives(array (
  0 => 
  array (
    0 => 'taglib',
    1 => 
    array (
      'prefix' => 'wui',
      'name' => 'tntwui',
    ),
  ),
), $this);
_smarty_load_plugins(array('plugins' => array(array('block', 'TNTWuiWidget', 'd:\\my webs 1\\tnt-synergy-3.0\\dev\\www\\includes\\libs\\tnt\\wui\\tests/simple.html', 23, false),)), $this); ?>
<?php
function _smarty_tplfunc_49db963e012013586829e4992ad2a59f_0(&$this)
{
$this->_tag_stack[] = array('TNTWuiWidget', array()); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_49db963e012013586829e4992ad2a59f_1(&$this)
{
$this->_tag_stack[] = array('TNTWuiWidget', array()); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Widgets Contents<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_49db963e012013586829e4992ad2a59f_2(&$this)
{
$this->_tag_stack[] = array('TNTWuiWidget', array('id' => 'w1')); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
  <?php $this->_tag_stack[] = array('TNTWuiWidget', array('id' => 'w11')); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
    <?php $this->_tag_stack[] = array('TNTWuiWidget', array('id' => 'w111')); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
    <?php $this->_tag_stack[] = array('TNTWuiWidget', array('id' => 'w112')); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
    <?php $this->_tag_stack[] = array('TNTWuiWidget', array('id' => 'w113')); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
      <?php $this->_tag_stack[] = array('TNTWuiWidget', array('id' => 'w1131')); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>
      <div><code>$w1131->Path() = <?php echo $this->_tpl_vars['w1131']->Path(); ?>
</code></div>
        <div><code>$self->Path() = <?php echo $this->_tpl_vars['self']->Path(); ?>
</code></div>
      <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
    <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
  <?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
  <?php $this->_tag_stack[] = array('TNTWuiWidget', array('id' => 'w12')); $_block_repeat=true;TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWidget::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}



?>
