<?php /* Smarty version 2.6.18, created on 2008-01-22 00:07:18
         compiled from d:%5Cmy+webs+1%5Ctnt-synergy-3.0%5Cdev%5Cwww%5Cincludes%5Clibs%5Ctnt%5Cwui%5Ctests/list.html */

$this->_cache_serials['d:/my webs 1/tnt-synergy-3.0/dev/www/temp/templates\%%0E^0EA^0EA87FC2%%list.html.inc'] = 'ff68629835fa9cc17a838a54661cd6f4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
_smarty_load_directives(array (
  0 => 
  array (
    0 => 'taglib',
    1 => 
    array (
      'prefix' => 'wui',
      'name' => 'tntwui',
    ),
  ),
), $this);
_smarty_load_plugins(array('plugins' => array(array('block', 'TNTWuiListBox', 'd:\\my webs 1\\tnt-synergy-3.0\\dev\\www\\includes\\libs\\tnt\\wui\\tests/list.html', 127, false),array('block', 'TNTWuiToggleList', 'd:\\my webs 1\\tnt-synergy-3.0\\dev\\www\\includes\\libs\\tnt\\wui\\tests/list.html', 191, false),)), $this); ?>
<?php
function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_0(&$this)
{
$this->_tag_stack[] = array('TNTWuiListBox', array('name' => 'list1','size' => '1','value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_1(&$this)
{
$this->_tag_stack[] = array('TNTWuiListBox', array('name' => 'list2','size' => '1','indent' => "&raquo;",'value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_2(&$this)
{
$this->_tag_stack[] = array('TNTWuiListBox', array('name' => 'list4','size' => '1','indent' => "&raquo;",'multiple' => true,'value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_3(&$this)
{
$this->_tag_stack[] = array('TNTWuiListBox', array('name' => 'list5','size' => '10','value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_4(&$this)
{
$this->_tag_stack[] = array('TNTWuiListBox', array('name' => 'list6','size' => '10','indent' => "&raquo;",'value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_5(&$this)
{
$this->_tag_stack[] = array('TNTWuiListBox', array('name' => 'list7','size' => '10','multiple' => true,'value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_6(&$this)
{
$this->_tag_stack[] = array('TNTWuiListBox', array('name' => 'list8','size' => '10','indent' => "&raquo;",'multiple' => true,'value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiListBox::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_7(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list9','value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_8(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list10','value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_9(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list11','multiple' => true,'value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_10(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list12','multiple' => true,'value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_11(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list13','cols' => '1','value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_12(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list14','cols' => '1','value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_13(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list15','cols' => '1','multiple' => true,'value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_14(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list16','cols' => '1','multiple' => true,'value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_15(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list17','cols' => '3','multiple' => 'true','style' => "background-color:cyan;",'value' => 'Devon','items' => $this->_tpl_vars['flat_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_ff68629835fa9cc17a838a54661cd6f4_16(&$this)
{
$this->_tag_stack[] = array('TNTWuiToggleList', array('name' => 'list18','cols' => '3','multiple' => 'true','style' => "background-color:cyan;",'value' => 'Devon','items' => $this->_tpl_vars['tree_items'])); $_block_repeat=true;TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiToggleList::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}



?>
