<?php /* Smarty version 2.6.18, created on 2008-01-18 01:26:19
         compiled from d:%5Cmy+webs+1%5Ctnt-synergy-3.0%5Cdev%5Cwww%5Cunittests%5Ctnt%5Cwui%5Ctests/window.html */

$this->_cache_serials['d:/my webs 1/tnt-synergy-3.0/dev/www/temp/templates\%%27^275^275BEB07%%window.html.inc'] = '4ae8f8169e6a2cb5b819acd4945d0b50';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
_smarty_load_directives(array (
  0 => 
  array (
    0 => 'taglib',
    1 => 
    array (
      'prefix' => 'wui',
      'name' => 'tntwui',
    ),
  ),
), $this);
_smarty_load_plugins(array('plugins' => array(array('block', 'TNTWuiWindow', 'd:\\my webs 1\\tnt-synergy-3.0\\dev\\www\\unittests\\tnt\\wui\\tests/window.html', 60, false),)), $this); ?>
<?php
function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_0(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Normal Window','width' => '300px','height' => '100px')); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_1(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Hidden Scroll Window','width' => '300px','height' => '100px','overflow' => 'hidden','align' => 'left')); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_2(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Overflow Scroll Window','width' => '300px','height' => '100px','overflow' => 'scroll','align' => 'right')); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_3(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Overflow Auto Window','width' => '300px','height' => '100px','overflow' => 'auto','align' => 'center')); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_4(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Overflow Marquee Up Window','width' => '300px','height' => '100px','overflow' => "marquee-up")); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_5(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Overflow Marquee Down Window','width' => '300px','height' => '100px','overflow' => "marquee-down")); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_6(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Overflow Marquee Left Window','width' => '300px','height' => '100px','overflow' => "marquee-left")); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_7(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => 'Overflow Marquee Right Window','width' => '300px','height' => '100px','overflow' => "marquee-right",'style' => "marquee-speed: 5;")); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_8(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => "Collapsable/Overflow Hidden Window",'width' => '300px','overflow' => 'hidden','collapsible' => true)); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}


function _smarty_tplfunc_4ae8f8169e6a2cb5b819acd4945d0b50_9(&$this)
{
$this->_tag_stack[] = array('TNTWuiWindow', array('title' => "Collapsable/Overflow Hidden Window",'width' => '300px','overflow' => 'hidden','collapsible' => 'true','style' => "padding: 10px; margin: 10px; border: 10px #cc0000 solid; overflow: hidden; background-color: #cc00cc; color: #00cc00;")); $_block_repeat=true;TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $this->_tpl_vars['content']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo TNTWuiWindow::_TemplatePluginBlock($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); 
}



?>
